### ISSUE TITLE
Cooperation with dplyrSparkSQL?

### ISSUE THREAD

**Issue by wush978** [RevolutionAnalytics/dplyr-spark#26]
Dear maintainers,

I wrote a similar experimental project [dplyrSparkSQL](https://github.com/bridgewell/dplyrSparkSQL) which borrows some functions from https://github.com/piersharding/dplyrimpaladb (https://github.com/piersharding/dplyrimpaladb/issues/2).

It works great in my work, so I would like to submit it to CRAN. Is it possible for us to cooperate and finish this task?

**Comment by wush978** [comment]
Btw, here is the features of dplyrSpark:
- Automatic installation if the user installs `maven` (no need to build spark)
- Support `filter`, `mutate`, `select` and some joining functions such as `left_join`. I only tested the functions I used in my work.

I hope these features are attracting.

**Comment by piccolbo** [comment]
Maybe we should have cooperated _before_ doing the work rather than _after_. What does cooperation mean now other than retiring one of the two projects? I normally do not submit my projects to CRAN because it makes it very hard to develop a serious test suite and, when external deps are present, downright impossible. There are also issues with copyright and license that would made it difficult to cooperate. So thanks, but no thanks.

**Comment by wush978** [comment]
I hope the proposal is not offensive. Cooperation might be retiring my package and let me help you develop yours. Cooperation might be retiring both of our projects and build a new project since both of the projects are experimental. I prefer cooperation because it might help the community more. That's all.

I agree that it would be better if we cooperate _before_ doing the work, but I did not know this project before.
